[package]
name = "df-audio-worklet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
deep_filter = { path = "../libDF/", default-features = false, features = [
  "tract",
] }
getrandom = { version = "0.2", default-features = false, features = ['js'], option = true }
ndarray = { version = "^0.15" }
# console_error_panic_hook = "0.1.7"
# wasm-bindgen = "0.2.100"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"   # Essential for smallest size
opt-level = 's'   # Optimize for size, or 'z' for even more aggressive

# [package.metadata.wasm-pack.profile.release]
# wasm-opt = ["-Oz", "--strip-debug", "--strip-dwarf", "--strip-producers"]
